# Generated by Django 6.0.6 on 2026-06-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_hkid'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('walkin', 'Walk-in'), ('appointment', 'Appointment'), ('emergency', 'Emergency')], default='walkin', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=100)),
                ('room_name', models.CharField(blank=True, default='', max_length=100)),
                ('consultation_start_time', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.patient')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
