# Generated by Django 6.0.6 on 2026-06-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queue_entry_model'),
    ]

    operations = [
    ]
