# Generated by Django 6.0.6 on 2026-06-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prescription_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='days_supply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
