# Generated by Django 6.0.6 on 2026-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_prescription_days_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='activemedication',
            name='days_supply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activemedication',
            name='diagnostic_result',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activemedication',
            name='item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activemedication',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('IV', 'IV'), ('IM', 'IM'), ('SC', 'SC'), ('topical', 'Topical'), ('inhalation', 'Inhalation')], default='oral', max_length=20),
        ),
        migrations.AddField(
            model_name='pastmedication',
            name='days_supply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastmedication',
            name='diagnostic_result',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pastmedication',
            name='item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pastmedication',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('IV', 'IV'), ('IM', 'IM'), ('SC', 'SC'), ('topical', 'Topical'), ('inhalation', 'Inhalation')], default='oral', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='diagnostic_result',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='item',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
