# Generated by Django 6.0.6 on 2026-07-12 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_standardize_medication_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeaveCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.TextField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_hkid', models.CharField(max_length=20)),
                ('consultation_details', models.TextField()),
                ('diagnosis', models.TextField()),
                ('recommended_sick_leave', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('qr_code_token', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('signature_timestamp', models.DateTimeField(auto_now_add=True)),
                ('revoked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leave_certificates', to='api.patient')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_views', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='api.sickleavecertificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
