# Generated by Django 6.0.6 on 2026-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sickleavecertificate_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='patient_hkid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sickleavecertificate',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
