# Generated by Django 6.0.6 on 2026-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_sickleavecertificate_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleavecertificate',
            name='doctor_display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
