# Generated by Django 6.0.6 on 2026-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sickleavecertificate_doctor_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate Counter',
                'verbose_name_plural': 'Certificate Counters',
            },
        ),
        migrations.AddField(
            model_name='sickleavecertificate',
            name='reference_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
