# Generated by Django 6.0.6 on 2026-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_certificatecounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleavecertificate',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
