# Generated by Django 6.0.6 on 2026-08-08 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sickleavecertificate_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_sequence', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Receipt Counter',
                'verbose_name_plural': 'Receipt Counters',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rref', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('doctor_email', models.EmailField(blank=True, max_length=254)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('clinic_address', models.TextField(blank=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_hkid', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('consultation', models.TextField()),
                ('medications', models.TextField(blank=True, default='')),
                ('investigations', models.TextField(blank=True, default='')),
                ('procedures', models.TextField(blank=True, default='')),
                ('misc', models.TextField(blank=True, default='')),
                ('consultation_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medications_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investigations_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('procedures_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_free', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_dollars', models.TextField()),
                ('diagnosis', models.TextField()),
                ('qr_code_token', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('signature_timestamp', models.DateTimeField(auto_now_add=True)),
                ('revoked_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
