# Generated by Django 6.0.6 on 2026-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_receiptcounter_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='consultation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
