# Generated by Django 6.0.6 on 2026-08-15 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_receipt_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('clinic_name', models.CharField(blank=True, max_length=255)),
                ('clinic_address', models.TextField(blank=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_hkid', models.CharField(blank=True, max_length=20)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(blank=True, default='', max_length=100)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_summary', to='api.sickleavecertificate')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_summaries', to='api.patient')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_summary', to='api.receipt')),
            ],
            options={
                'verbose_name': 'Visit Summary',
                'verbose_name_plural': 'Visit Summaries',
                'ordering': ['-visit_date'],
            },
        ),
    ]
