# Generated by Django 6.0.6 on 2026-07-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clinic_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
