# Generated by Django 6.0.6 on 2026-06-09 10:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('unit', models.CharField(choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('L', 'Liters'), ('TAB', 'Tablets'), ('CAP', 'Capsules'), ('IU', 'International Units')], max_length=10)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dosage_strength', models.CharField(max_length=100)),
                ('administration_route', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('BID', 'Twice daily'), ('TID', 'Three times daily'), ('QID', 'Four times daily'), ('PRN', 'As needed'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('dosage_instructions', models.JSONField(default=dict)),
                ('side_effects', models.TextField()),
                ('contraindications', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('stock_value', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=10, help_text='Alert when stock drops below this level')),
                ('max_stock_level', models.PositiveIntegerField(default=1000, help_text='Restock target level')),
                ('supplier_name', models.CharField(db_index=True, max_length=255)),
                ('supplier_contact', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=20)),
                ('supplier_address', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('expiry_date', models.DateField(db_index=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_stock_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name', 'category'],
                'indexes': [models.Index(fields=['name', 'category'], name='medication__name_fb4f36_idx'), models.Index(fields=['expiry_date'], name='medication__expiry__bf0055_idx'), models.Index(fields=['stock_value'], name='medication__stock_v_e66d8a_idx'), models.Index(fields=['supplier_name'], name='medication__supplie_6a4cd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_stock_value', models.PositiveIntegerField()),
                ('new_stock_value', models.PositiveIntegerField()),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medication')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
