# Generated by Django 6.0.6 on 2026-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='threshold_stock_value',
            field=models.PositiveIntegerField(blank=True, help_text='Stock level at which to trigger low stock alert', null=True),
        ),
    ]
